### ISSUE TITLE
Не билдер, а фабрика?

### ISSUE THREAD

**Issue by katleta3000** [alfa-laboratory/YARCH-Examples#34]
@iltsarev @imJustik Привет! По-моему, то что собирает модуль (например, `CatalogBuilder`) - это конкретная фабрика, а не билдер.
**Билдер** - строит комплексный объект из частей. Например, если мы программно создаём `ViewController` – то мы используем билдер, который создаёт `UILabel`, `UIView`, задаёт их стили, расставляет констрейнты.
**Фабрика** - создаёт группу взаимосвязанных объектов, проставляет связи между ними при условии, что объекты не могут существовать без друг друга.

Интересно ваше мнение услышать? Мы называет это фабриками.

**Comment by dehrom** [comment]
Широко применяем возможности изменения конфигурации создаваемого объекта (`UIViewController`'a), что позволяет нам изменить логику работы в смежных кейсах (SigIn/SignUp к примеру). Соблюдаются все теребования паттерна:
- абстрагирование от процесса создания
- изменяемость внутреннего представления конечного объекта от параметров указанных в ходе конструирования

Кажется что в случае применения фабрики был бы не `LoginModuleBuilder` а `AuthModuleFactory` и `RegistrationModuleFactory`.

**Comment by aeternas** [comment]
Полагаю, можно закрыть.
